# Generated by Django 2.2.6 on 2019-11-22 15:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Enter the slug of the page, this will be the url. Must be unique.', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Enter the title of the page.', max_length=65)),
                ('body', ckeditor.fields.RichTextField(help_text='Enter the body of the page, html is allowed')),
            ],
        ),
    ]
