# Generated by Django 2.2.6 on 2019-10-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Enter the slug of the page, this will be the url. html is not allowed', max_length=20)),
                ('title', models.CharField(help_text='Enter the title of the page, html is not allowed', max_length=65)),
                ('body', models.TextField(help_text='Enter the body of the page, html is allowed')),
                ('is_malicious', models.BooleanField(default=False)),
            ],
        ),
    ]
