# Generated by Django 2.2.6 on 2019-10-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(help_text='Enter the slug of the page, this will be the url. Must be unique.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='Enter the title of the page.', max_length=65),
        ),
    ]
